[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/check"
  to = "/.netlify/functions/check"
  status = 200

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
  foce = true

